const BRAND_LOGOS = [
    { name: 'Shell', url: 'https://images.icon-icons.com/2699/PNG/512/shell_logo_icon_168832.png' },
    { name: 'Mobil', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Mobil_logo.svg/3840px-Mobil_logo.svg.png' },
    { name: 'Terpel', url: 'https://portalcolombia.terpel.com/static/images/terpel_logo_og.png' },
    { name: 'Chevron', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Chevron_Logo.svg/960px-Chevron_Logo.svg.png' },
    { name: 'Repsol', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Repsol_logo.svg/1280px-Repsol_logo.svg.png' },
    { name: '3M', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/3M_wordmark.svg/3840px-3M_wordmark.svg.png' },
    { name: 'Castrol', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Castrol_logo_2023.svg/3840px-Castrol_logo_2023.svg.png' },
    { name: 'Valvoline', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Valvoline_company_logo.svg/1280px-Valvoline_company_logo.svg.png' },
    { name: 'Gulf', url: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Gulf_logo.png' },
    { name: 'Motul', url: 'https://1000marcas.net/wp-content/uploads/2021/05/Logo-Motul.png' },
    { name: 'MCR Safety', url: 'https://ibtinc.com/wp-content/uploads/2022/12/MCR-Safety-logo.png' },
    { name: 'Ansell', url: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Ansell_logo.svg/3840px-Ansell_logo.svg.png' },
    { name: 'Bosch', url: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Bosch_logo.png' },
    { name: 'ARO', url: 'https://sumicali.com/cdn/shop/collections/ARO-Sumicali.png?crop=center&height=2048&v=1716414249&width=2048' },
];
